[information]
name = "noxmodus"
background = "dark"
author = "Lano Puljic"


[palette]
bg                          = '#1d1f20'
fg                          = '#999999'
gray01                      = '#333333'
gray02                      = '#666666'
gray03                      = '#c9c9c9'
gray04                      = '#7c8c95'
gray05                      = '#8c8c8c'
gray06                      = '#a0a0a0'
gray08                      = '#efefef'
green                       = '#73C991'
blue                        = '#719597'
purple                      = '#B180D7'
red                         = '#db4b4b'
orange                      = '#fe8019'
yellow                      = '#f2ac46'
sage_green                  = '#B2AC88'
cursor_fg                   = '#415062'
cursor_bg                   = '#AbAbAf'


[editor]
# Misc
Normal                      = 'gray03 bg'
Cursor                      = 'cursor_fg cursor_bg'
Underlined                  = '- - u'
SpecialKey                  = 'fg - b'
NonText                     = 'gray02'
Insert                      = 'red orange'
MsgArea                     = 'fg bg'

# Lines
LineNr                      = 'gray06 -'
CursorLineNr                = 'gray08 gray01'
CursorLine                  = '- gray01'
SignColumn                  = '- bg'
ColorColumn                 = '- gray06'
CursorColumn                = '- gray01'

# Spelling
SpellBad                    = '- - c red'
SpellCap                    = '- - c yellow'
SpellLocal                  = '- - u green'
SpellRare                   = '- - u purple'

# Messages
ErrorMsg                    = 'red bg b'
WarningMsg                  = 'orange bg'
ModeMsg                     = 'fg bg'
MoreMsg                     = 'yellow'
Error                       = 'red - b'

# Visual
Visual                      = '- gray01'
VisualNOS                   = '- red'
Search                      = 'bg gray08'
IncSearch                   = 'bg gray08'

# Popup Menu
Pmenu                       = 'fg gray01'
PmenuSel                    = 'bg gray03'
PmenuSbar                   = 'fg gray01'
PmenuThumb                  = 'fg gray03'         # Changes colour of scroll bar in floating window.

# Diff
DiffText                    = 'bg red'
DiffAdd                     = 'bg green'
DiffChange                  = 'bg orange u'
DiffDelete                  = 'bg red'

# Others

NormalNC                    = 'fg bg'
WildMenu                    = 'fg bg'
Folded                      = 'gray02 -'
FoldColumn                  = 'gray06 -'
Whitespace                  = 'fg'
NormalFloat                 = '- -'               # Changes background on floating windows 
FloatBoder                  = 'gray03 bg'
QuickFixLine                = '- yellow'
MatchWord                   = '- - u'
MatchParen                  = 'orange'
MatchWordCur                = '- - u'
MatchParenCur               = '- - u'
lCursor                     = 'cursor_fg cursor_bg'
CursorIM                    = 'cursor_fg cursor_bg'
TermCursor                  = 'cursor_fg cursor_bg'
TermCursorNC                = 'cursor_fg cursor_bg'
Conceal                     = 'fg'
Directory                   = 'gray06'
Substitute                  = 'bg gray03'
Question                    = 'yellow'
EndOfBuffer                 = 'bg'
TabLine                     = 'gray06 bg'
TabLineSel                  = 'fg bg'
TabLineFill                 = 'bg bg'

[code]
Comment                     = 'gray02 - i'
Title                       = 'gray05 - b'
String                      = 'gray03'
Character                   = 'gray03'
Number                      = 'gray04'
Float                       = 'gray04'
Boolean                     = 'gray04'
Constant                    = 'gray03'
Type                        = 'gray03'          # int, long, char, etc.  
StorageClass                = 'gray03'          # static, register, volatile
Structure                   = 'gray03'          # struct, union, enum
Typedef                     = 'gray03'          # A typedef
PreProc                     = 'sage_green'      # was gray05
Include                     = 'gray05'
Define                      = 'gray05'
Macro                       = 'gray05'
PreCondit                   = 'gray05'
Statement                   = 'gray03'
Conditional                 = 'gray03'          # if, then, else, endif
Repeat                      = 'gray03'          # for, do, while
Label                       = 'gray03'          # case, default,
Operator                    = 'gray03'          # " =, >=, :="
Keyword                     = 'gray03'
Exception                   = 'gray03'          # try, catch, throw
Identifier                  = 'sage_green'
Function                    = '-' # was gray08
Special                     = 'gray03'          # ${, [], ?
SpecialChar                 = 'gray03'
Tag                         = 'gray03'
Delimiter                   = 'gray03'
Debug                       = 'gray03'
Bold                        = '- - b'
Italic                      = '- - i'
Ignore                      = 'red - b'
Todo                        = 'red - b'
Variable                    = 'red'

[StatusLine]    
StatusLine                  = 'gray03 gray01'
StatusLineNC                = 'gray02 gray01'
StatusLineSeparator         = 'gray03'
StatusLineTerm              = 'gray03'
StatusLineTermNC            = 'gray03'

[git]
SignAdd                     = 'green'
SignChange                  = 'orange'
SignDelete                  = 'red'
GitSignsAdd                 = 'green'
GitSignsChange              = 'orange'
GitSignsDelete              = 'red'

[packer]
packerString                = 'orange'
packerHash                  = 'blue'
packerOutput                = 'purple'
packerRelDate               = 'gray03'
packerSuccess               = 'green'
packerStatusSuccess         = 'blue'

[cmp]
CmpItemAbbrDeprecated       = 'gray03 - s'
CmpItemAbbrMatch            = 'gray08'
CmpItemAbbrMatchFuzzy       = 'gray03'

CmpItemKindFunction         = 'gray08'
CmpItemKindMethod           = 'gray08'
CmpItemKindConstructor      = 'gray08'
CmpItemKindClass            = 'gray08'
CmpItemKindEnum             = 'gray08'
CmpItemKindEvent            = 'gray08'
CmpItemKindInterface        = 'gray08'
CmpItemKindStruct           = 'gray08'
CmpItemKindVariable         = 'gray08'
CmpItemKindField            = 'gray08'
CmpItemKindProperty         = 'gray08'
CmpItemKindEnumMember       = 'gray08'
CmpItemKindConstant         = 'gray08'
CmpItemKindKeyword          = 'gray08'
CmpItemKindModule           = 'gray08'
CmpItemKindValue            = 'gray08'
CmpItemKindUnit             = 'gray08'
CmpItemKindText             = 'gray08'
CmpItemKindSnippet          = 'gray08'
CmpItemKindFile             = 'gray08'
CmpItemKindFolder           = 'gray08'
CmpItemKindColor            = 'gray08'
CmpItemKindReference        = 'gray08'
CmpItemKindOperator         = 'gray08'
CmpItemKindTypeParameter    = 'gray08'

[NvimTree]
NvimTreeGitNew              = 'green'
NvimTreeGitRenamed          = 'green'
NvimTreeGitDeleted          = 'red'
NvimTreeGitMerge            = 'orange'
NvimTreeGitStaged           = 'green'
NvimTreeGitDirty            = 'yellow'
NvimTreeSymlink             = 'blue'

[Telescope]
TelescopeMatching           = 'blue - bi'
TelescopePromptPrefix       = "blue"
TelescopePromptTitle        = "orange - b"
TelescopeResultsTitle       = "orange - b"
TelescopePreviewTitle       = "orange - b"
TelescopePreviewHyphen      = "red"

[Navic]
NavicIconsFile              = 'gray08'
NavicIconsModule            = 'gray08'
NavicIconsNamespace         = 'gray08'
NavicIconsPackage           = 'gray08'
NavicIconsClass             = 'gray08'
NavicIconsMethod            = 'gray08'
NavicIconsProperty          = 'gray08'
NavicIconsField             = 'gray08'
NavicIconsConstructor       = 'gray08'
NavicIconsEnum              = 'gray08'
NavicIconsInterface         = 'gray08'
NavicIconsFunction          = 'gray08'
NavicIconsVariable          = 'gray08'
NavicIconsConstant          = 'gray08'
NavicIconsString            = 'gray08'
NavicIconsNumber            = 'gray08'
NavicIconsBoolean           = 'gray08'
NavicIconsArray             = 'gray08'
NavicIconsObject            = 'gray08'
NavicIconsKey               = 'gray08'
NavicIconsKeyword           = 'gray08'
NavicIconsNull              = 'gray08'
NavicIconsEnumMember        = 'gray08'
NavicIconsStruct            = 'gray08'
NavicIconsEvent             = 'gray08'
NavicIconsOperator          = 'gray08'
NavicIconsTypeParameter     = 'gray08'
NavicText                   = 'gray05'
NavicSeparator              = 'gray04'